name: Generate Static Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/data/**'

jobs:
  generate-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install handlebars fs-extra
    
    - name: Generate pages
      run: |
        node ./scripts/generate-pages.js
        cp -r src/assets docs/assets
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
